name: CarthagoGuide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.0.5
  video_player: ^2.9.2
  lottie: ^3.3.1
  font_awesome_flutter: ^10.9.1
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  transformable_list_view: ^0.7.0
  audioplayers: ^6.5.1
  go_router: ^17.0.0
  http: ^1.1.0
  uuid: ^4.3.3
  flutter_markdown: ^0.6.18
  speech_to_text: ^7.3.0
  permission_handler: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/videos/tgt.mp4
  - assets/videos/video2.mp4
  - assets/images/
  - assets/images/circuit1.jpg
  - assets/sounds/
  - assets/sounds/punic.mp3
  - assets/sounds/roman.mp3
  - assets/sounds/islamic.mp3
  - assets/sounds/modern.mp3
  - assets/sounds/independence.mp3

